version: "3.1"

services:
  web:
    build: .
    image: bacula-web-docker:latest
    ports:
      - "8080:80"
    environment:
      BW_LANGUAGE: ""
      BW_LABEL: ""
      BW_HOST: "" 
      BW_LOGIN: ""
      BW_PASSWORD: ""
      BW_DB_NAME: ""
      BW_DB_TYPE: ""
      BW_DB_PORT: ""
    container_name: "bacula_web"